<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
      <key>begin</key>
      <string>\s*(function)\s+(?=[[:alpha:]_][[:alnum:]_]*)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.modifier.async.ezlanguage</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>storage.type.function.ezlanguage</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\()|\s*($\n?|#.*$\n?)</string>
      <key>name</key>
      <string>meta.function.ezlanguage</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(?=[[:alpha:]_][[:alnum:]_]*)</string>
          <key>contentName</key>
          <string>entity.name.function.ezlanguage</string>
          <key>end</key>
          <string>(?![[:alnum:]_])</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#entity_name_function</string>
            </dict>
          </array>
        </dict>
      </array>
      <key>returns</key>
      <string>\s*(returns)\s+(?=[[:alpha:]_]*)</string>
      <key>returnsCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.modifier.async.ezlanguage</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>storage.type.function.ezlanguage</string>
        </dict>
      </dict>
    </dict>
</plist>