<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>ez</string>
    <string>ezl</string>
    <string>ezlanguage</string>
  </array>
  <key>firstLineMatch</key>
  <string>^#!/.*\ezlanguage[\d\.]*\b</string>
  <key>keyEquivalent</key>
  <string>^~P</string>
  <key>name</key>
  <string>EZLanguage</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>match</key>
      <string>(?&lt;!|^import\s)(\.{3})</string>
      <key>name</key>
      <string>support.type.ellipsis.ezlanguage</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#comment</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>Match identifiers in ALL_CAPS as constants, except when followed by `.`, `(`, `'`, or `"`.</string>
      <key>match</key>
      <string>\b([[:upper:]_][[:upper:][:digit:]_]*)\b(?![\.\(\'\"])</string>
      <key>name</key>
      <string>constant.other.allcaps.ezlanguage</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(?i:(\d+\.\d*(e[\-\+]?\d+)?))(?=[^[:alpha:]_])</string>
      <key>name</key>
      <string>constant.numeric.float.ezlanguage</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(?&lt;=[^[:alnum:]_])(?i:(\.\d+(e[\-\+]?\d+)?))</string>
      <key>name</key>
      <string>constant.numeric.float.ezlanguage</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(?i:(\d+e[\-\+]?\d+))</string>
      <key>name</key>
      <string>constant.numeric.float.ezlanguage</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b([1-9]+[0-9]*|0)</string>
      <key>name</key>
      <string>constant.numeric.integer.decimal.ezlanguage</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(true|false|True|False)\b</string>
      <key>name</key>
      <string>constant.language.ezlanguage</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(global)\b</string>
      <key>name</key>
      <string>storage.modifier.$1.ezlanguage</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(?:(import|include))\b</string>
      <key>name</key>
      <string>keyword.control.import.$1.ezlanguage</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>keyword operators that evaluate to True or False</string>
      <key>match</key>
      <string>\b(and|in|is|not|or)\b</string>
      <key>name</key>
      <string>keyword.operator.logical.ezlanguage</string>
    </dict>
    <dict>
      <key>match</key>
      <string>&lt;\=|&gt;\=|\=\=|&lt;|&gt;|\!\=</string>
      <key>name</key>
      <string>keyword.operator.comparison.ezlanguage</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\+\=|-\=|\*\=|/\=|%\=|&amp;\=|\|\=|\^\=|&gt;&gt;\=|&lt;&lt;\=|\*\*\=|@\=</string>
      <key>name</key>
      <string>keyword.operator.assignment.augmented.ezlanguage</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\+|\-|\*|\*\*|/|%|&lt;&lt;|&gt;&gt;|&amp;|\||\^|~|(?!^)@</string>
      <key>name</key>
      <string>keyword.operator.arithmetic.ezlanguage</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\=</string>
      <key>name</key>
      <string>keyword.operator.assignment.ezlanguage</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>^\s*(class)\s+(?=[[:alpha:]_][[:alnum:]_]*\s*\:)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.type.class.ezlanguage</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>entity.name.type.class.ezlanguage</string>
      <key>end</key>
      <string>\s*(:)</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.class.begin.ezlanguage</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.class.old-style.ezlanguage</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#entity_name_class</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>begin</key>
      <string>^\s*(class)\s+(?=[[:alpha:]_][[:alnum:]_]*\s*\()</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.type.class.ezlanguage</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\))\s*(?:(\:)|(.*$\n?))</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.inheritance.end.ezlanguage</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.class.begin.ezlanguage</string>
        </dict>
        <key>3</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.missing-section-begin.ezlanguage</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.class.ezlanguage</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(?=[[:alpha:]_][[:alnum:]_]*)</string>
          <key>contentName</key>
          <string>entity.name.type.class.ezlanguage</string>
          <key>end</key>
          <string>(?![[:alnum:]_])</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#entity_name_class</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.inheritance.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>meta.class.inheritance.ezlanguage</string>
          <key>end</key>
          <string>(?=\)|:)</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>begin</key>
              <string>(?&lt;=\(|,)\s*</string>
              <key>contentName</key>
              <string>entity.other.inherited-class.ezlanguage</string>
              <key>end</key>
              <string>\s*(?:(,)|(?=\)))</string>
              <key>endCaptures</key>
              <dict>
                <key>1</key>
                <dict>
                  <key>name</key>
                  <string>punctuation.separator.inheritance.ezlanguage</string>
                </dict>
              </dict>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>$self</string>
                </dict>
              </array>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <dict>
      <key>begin</key>
      <string>^\s*(class)\s+(?=[[:alpha:]_][[:alnum:]_]*)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.type.class.ezlanguage</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\()|(\s*$\n?|#.*$\n?)</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.inheritance.begin.ezlanguage</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.missing-inheritance.ezlanguage</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.class.ezlanguage</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(?=[[:alpha:]_][[:alnum:]_]*)</string>
          <key>contentName</key>
          <string>entity.name.type.class.ezlanguage</string>
          <key>end</key>
          <string>(?![[:alnum:]_])</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#entity_name_function</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <dict>
      <key>begin</key>
      <string>\s*(procedureTODO)\s+(?=[[:alpha:]_][[:alnum:]_]*\s*\()</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.modifier.async.ezlanguage</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>storage.type.function.ezlanguage</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\:)</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.function.begin.ezlanguage</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.function.ezlanguage</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(?=[[:alpha:]_][[:alnum:]_]*)</string>
          <key>contentName</key>
          <string>entity.name.function.ezlanguage</string>
          <key>end</key>
          <string>(?![[:alnum:]_])</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#entity_name_function</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.parameters.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>meta.function.parameters.ezlanguage</string>
          <key>end</key>
          <string>(?=\)\s*(?:\:|-\&gt;))</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#annotated_arguments</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#keyword_arguments</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#comment</string>
            </dict>
            <dict>
              <key>captures</key>
              <dict>
                <key>1</key>
                <dict>
                  <key>name</key>
                  <string>variable.parameter.function.language.ezlanguage</string>
                </dict>
                <key>2</key>
                <dict>
                  <key>name</key>
                  <string>variable.parameter.function.ezlanguage</string>
                </dict>
                <key>3</key>
                <dict>
                  <key>name</key>
                  <string>punctuation.separator.parameters.ezlanguage</string>
                </dict>
              </dict>
              <key>match</key>
              <string>\b(?:(self|cls)|([[:alpha:]_][[:alnum:]_]*))\s*(?:(,)|(?=[\n\)]))</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\))\s*(\-&gt;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.parameters.end.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.separator.annotation.result.ezlanguage</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?=\:)</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <dict>
      <key>begin</key>
      <string>\s*(procedure)\s+(?=[[:alpha:]_][[:alnum:]_]*)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.modifier.async.ezlanguage</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>storage.type.function.ezlanguage</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\()|\s*($\n?|#.*$\n?)</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.parameters.begin.ezlanguage</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.missing-parameters.ezlanguage</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.function.ezlanguage</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(?=[[:alpha:]_][[:alnum:]_]*)</string>
          <key>contentName</key>
          <string>entity.name.function.ezlanguage</string>
          <key>end</key>
          <string>(?![[:alnum:]_])</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#entity_name_function</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <dict>
      <key>comment</key>
      <string>Keywords that delimit flow blocks or alter flow from within a
             block.

             This block should be matched *after* meta.function.ezlanguage to
             let 'async def' be matched *first*.
             </string>
      <key>match</key>
      <string>(?x) \b(
            elif | else | then | for | if | return | while | when | begin | end | do | step |
            program | is | in | of | or |
            (yield(?:\s+from)?)
          )\b
          </string>
      <key>name</key>
      <string>keyword.control.flow.ezlanguage</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>(lambda)(?=\s+|:)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.type.function.inline.ezlanguage</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\:)</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.parameters.end.ezlanguage</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.function.begin.ezlanguage</string>
        </dict>
        <key>3</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.missing-section-begin.ezlanguage</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.function.inline.ezlanguage</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>\s+</string>
          <key>contentName</key>
          <string>meta.function.inline.parameters.ezlanguage</string>
          <key>end</key>
          <string>(?=\:)</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#keyword_arguments</string>
            </dict>
            <dict>
              <key>captures</key>
              <dict>
                <key>1</key>
                <dict>
                  <key>name</key>
                  <string>variable.parameter.function.ezlanguage</string>
                </dict>
                <key>2</key>
                <dict>
                  <key>name</key>
                  <string>punctuation.separator.parameters.ezlanguage</string>
                </dict>
              </dict>
              <key>match</key>
              <string>\b([[:alpha:]_][[:alnum:]_]*)\s*(?:(,)|(?=[\n\)\:]))</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <dict>
      <key>begin</key>
      <string>^\s*(?=@\s*[[:alpha:]_][[:alnum:]_]*(?:\s*\.\s*[[:alpha:]_][[:alnum:]_]*)*\s*\()</string>
      <key>comment</key>
      <string>a decorator may be a function call which returns a decorator.</string>
      <key>end</key>
      <string>(\))</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.arguments.end.ezlanguage</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.function.decorator.ezlanguage</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(?=(@)\s*[[:alpha:]_][[:alnum:]_]*(?:\s*\.\s*[[:alpha:]_][[:alnum:]_]*)*\s*\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.decorator.ezlanguage</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>entity.name.function.decorator.ezlanguage</string>
          <key>end</key>
          <string>(?=\s*\()</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#dotted_name</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.arguments.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>meta.function.decorator.arguments.ezlanguage</string>
          <key>end</key>
          <string>(?=\))</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#keyword_arguments</string>
            </dict>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <dict>
      <key>begin</key>
      <string>^\s*(?=@\s*[[:alpha:]_][[:alnum:]_]*(?:\s*\.\s*[[:alpha:]_][[:alnum:]_]*)*)</string>
      <key>contentName</key>
      <string>entity.name.function.decorator.ezlanguage</string>
      <key>end</key>
      <string>(?=\s|$\n?|#)</string>
      <key>name</key>
      <string>meta.function.decorator.ezlanguage</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(?=(@)\s*[[:alpha:]_][[:alnum:]_]*(\s*\.\s*[[:alpha:]_][[:alnum:]_]*)*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.decorator.ezlanguage</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?=\s|$\n?|#)</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#dotted_name</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <dict>
      <key>begin</key>
      <string>(?&lt;=\)|\])\s*(\()</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.arguments.begin.ezlanguage</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>meta.function-call.arguments.ezlanguage</string>
      <key>end</key>
      <string>(\))</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.arguments.end.ezlanguage</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.function-call.ezlanguage</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#keyword_arguments</string>
        </dict>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>include</key>
      <string>#builtin_types</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#builtin_functions_name</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#builtin_functions_call</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#errors_warnings_exceptions</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#magic_function_names</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#magic_function_calls</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#docstrings</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#magic_variable_names</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#language_variables</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#generic_object_names</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>(?:\.)?([[:alpha:]_][[:alnum:]_]*)\s*(?=(\())</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>meta.function-call.generic.ezlanguage</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\))</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.arguments.end.ezlanguage</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.function-call.ezlanguage</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.arguments.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>meta.function-call.arguments.ezlanguage</string>
          <key>end</key>
          <string>(?=\))</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#keyword_arguments</string>
            </dict>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <dict>
      <key>comment</key>
      <string>Py2 print statement that should only be matched after function calls</string>
      <key>match</key>
      <string>(?&lt;!\.)\b(print)(?=\s|$)</string>
      <key>name</key>
      <string>keyword.other.print.ezlanguage</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>(?=[[:alpha:]_][[:alnum:]_]*(?:\s*\.\s*[[:alpha:]_][[:alnum:]_]*)*\s*\[)</string>
      <key>end</key>
      <string>(\])</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.arguments.end.ezlanguage</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.item-access.ezlanguage</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(?=[[:alpha:]_][[:alnum:]_]*(?:\s*\.\s*[[:alpha:]_][[:alnum:]_]*)*\s*\[)</string>
          <key>end</key>
          <string>(?=\s*\[)</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#dotted_name</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.arguments.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>meta.item-access.arguments.ezlanguage</string>
          <key>end</key>
          <string>(?=\])</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>\G</string>
          <key>end</key>
          <string>(?=\[)</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#dotted_name</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.type.class.ezlanguage</string>
        </dict>
      </dict>
      <key>match</key>
      <string>\b(class)\b</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#line_continuation</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#string_quoted_single</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#string_quoted_double</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#dotted_name</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>(\()</string>
      <key>end</key>
      <string>(\))</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.list.begin.ezlanguage</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>meta.empty-list.ezlanguage</string>
        </dict>
        <key>3</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.list.end.ezlanguage</string>
        </dict>
      </dict>
      <key>match</key>
      <string>(\[)(\s*(\]))\b</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>(\[)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.list.begin.ezlanguage</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\])</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.list.end.ezlanguage</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.structure.list.ezlanguage</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(?&lt;=\[|\,)\s*(?![\],])</string>
          <key>contentName</key>
          <string>meta.structure.list.item.ezlanguage</string>
          <key>end</key>
          <string>\s*(?:(,)|(?=\]))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.separator.list.ezlanguage</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.dictionary.begin.ezlanguage</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>meta.empty-dictionary.ezlanguage</string>
        </dict>
        <key>3</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.dictionary.end.ezlanguage</string>
        </dict>
      </dict>
      <key>match</key>
      <string>(\{)(\s*(\}))</string>
      <key>name</key>
      <string>meta.structure.dictionary.ezlanguage</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>(\{)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.dictionary.begin.ezlanguage</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\})</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.dictionary.end.ezlanguage</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.structure.dictionary.ezlanguage</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(?&lt;=\{|\,|^)\s*(?![\},])</string>
          <key>contentName</key>
          <string>meta.structure.dictionary.key.ezlanguage</string>
          <key>end</key>
          <string>\s*(?:(?=\})|(\:))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.separator.valuepair.dictionary.ezlanguage</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?&lt;=\:|^)\s*</string>
          <key>contentName</key>
          <string>meta.structure.dictionary.value.ezlanguage</string>
          <key>end</key>
          <string>\s*(?:(?=\})|(,))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.separator.dictionary.ezlanguage</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>annotated_arguments</key>
    <dict>
      <key>begin</key>
      <string>\b([[:alpha:]_][[:alnum:]_]*)\s*(:)|(?=\()</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.function.ezlanguage</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>punctuation.separator.annotation.ezlanguage</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\s*(?:(,)|(?=$\n?|[\)\:]))</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.separator.parameters.ezlanguage</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#annotated_group</string>
        </dict>
        <dict>
          <key>match</key>
          <string>=</string>
          <key>name</key>
          <string>keyword.operator.assignment.ezlanguage</string>
        </dict>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
    <key>annotated_group</key>
    <dict>
      <key>begin</key>
      <string>(\()</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.parameters-group.begin.ezlanguage</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\))</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.parameters-group.end.ezlanguage</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>\b([[:alpha:]_][[:alnum:]_]*)\s*(:)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.parameter.function.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.separator.annotation.ezlanguage</string>
            </dict>
          </dict>
          <key>end</key>
          <string>\s*(?:(,)|(?=$\n?|\)))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.separator.parameters.ezlanguage</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>\b([[:alpha:]_][[:alnum:]_]*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.parameter.function.ezlanguage</string>
            </dict>
          </dict>
          <key>end</key>
          <string>\s*(?:(,)|(?=$\n?|\)))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.separator.parameters.ezlanguage</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
      </array>
    </dict>
    <key>builtin_functions_call</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(?x)
              (?&lt;!\.)\b(
                __import__ | abs | boolean | string |
                bytearray | bytes | complex | dir | exec | file | float | input | integer | array |
                list | long | map |	max | next | open | pow | print | property | range | type | set
              )
              \b\s*(?=\()
              </string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.function.builtin.call.ezlanguage</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.arguments.end.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>meta.function-call.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>begin</key>
              <string>(?=[[:alpha:]_][[:alnum:]_]*(?:\s*\.\s*[[:alpha:]_][[:alnum:]_]*)*\s*\()</string>
              <key>end</key>
              <string>(?=\s*\()</string>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>#dotted_name</string>
                </dict>
              </array>
            </dict>
            <dict>
              <key>begin</key>
              <string>(\()</string>
              <key>beginCaptures</key>
              <dict>
                <key>1</key>
                <dict>
                  <key>name</key>
                  <string>punctuation.definition.arguments.begin.ezlanguage</string>
                </dict>
              </dict>
              <key>contentName</key>
              <string>meta.function-call.arguments.ezlanguage</string>
              <key>end</key>
              <string>(?=\))</string>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>#keyword_arguments</string>
                </dict>
                <dict>
                  <key>include</key>
                  <string>$self</string>
                </dict>
              </array>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>builtin_functions_name</key>
    <dict>
      <key>match</key>
      <string>(?x)
          (?&lt;!\.|@)
              \b(
            __import__ | abs | boolean | string |
            bytearray | bytes | complex | dir | exec | file | float | input | integer |
            len | list | locals | long | map | array |
            max | next | open | pow | print | property | range | type | set
          )
          \b\s*(?!(\())</string>
      <key>name</key>
      <string>support.function.builtin.name.ezlanguage</string>
    </dict>
    <key>builtin_types</key>
    <dict>
      <key>comment</key>
      <string>These are from https://docs.python.org/X/library/stdtypes.html
                  where X is 2.7 or 3.5.</string>
      <key>match</key>
      <string>(?x)
            (?&lt;!\.)
            \b(
              boolean | bytearray | bytes | complex | float |
              integer | list | long | range | set | type )
            \b(?!(\s*\())</string>
      <key>name</key>
      <string>support.type.ezlanguage</string>
    </dict>
    <key>comment</key>
    <dict>
      <key>begin</key>
      <string>(^[ \t]+)?(?=#)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.whitespace.comment.leading.ezlanguage</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(?!\G)</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>#</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.ezlanguage</string>
            </dict>
          </dict>
          <key>end</key>
          <string>\n</string>
          <key>name</key>
          <string>comment.line.number-sign.ezlanguage</string>
        </dict>
      </array>
    </dict>
    <key>constant_placeholder</key>
    <dict>
      <key>match</key>
      <string>(?i:(%(\([[:lower:]_]+\))?#?0?\-?[ ]?\+?([0-9]*|\*)(\.([0-9]*|\*))?[hL]?[[:lower:]%])|(\{([!\[\].:\w ]+)?\}))</string>
      <key>name</key>
      <string>constant.other.placeholder.ezlanguage</string>
    </dict>
    <key>docstrings</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>^\s*(?=[uU]?[rR]?""")</string>
          <key>end</key>
          <string>(?&lt;=""")</string>
          <key>name</key>
          <string>comment.block.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#string_quoted_double</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>^\s*(?=[uU]?[rR]?''')</string>
          <key>end</key>
          <string>(?&lt;=''')</string>
          <key>name</key>
          <string>comment.block.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#string_quoted_single</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>dotted_name</key>
    <dict>
      <key>begin</key>
      <string>(?=(?:\.(?!\s+import)\s*)?[[:alpha:]_][[:alnum:]_]*(?:\s*\.\s*[[:alpha:]_][[:alnum:]_]*)*)</string>
      <key>end</key>
      <string>(?![[:alnum:]_\.\s])|(?=(?&lt;!\.)\s+[^.])|$</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(\.)(?=[[:alpha:]_][[:alnum:]_]*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>meta.dot.ezlanguage</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?![[:alnum:]_])</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#builtin_functions_name</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#magic_function_names</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#magic_variable_names</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#generic_names</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#illegal_names</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?&lt;!\.)(?=[[:alpha:]_][[:alnum:]_]*)</string>
          <key>end</key>
          <string>(?![[:alnum:]_])</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#builtin_types</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#builtin_functions_name</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#builtin_functions_call</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#errors_warnings_exceptions</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#magic_function_names</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#magic_function_calls</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#magic_variable_names</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#language_variables</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#generic_names</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#illegal_names</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>entity_name_class</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#generic_names</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal_names</string>
        </dict>
      </array>
    </dict>
    <key>entity_name_function</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#builtin_functions_name</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#magic_function_names</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal_names</string>
        </dict>
      </array>
    </dict>
    <key>escaped_char</key>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>constant.character.escape.hex.ezlanguage</string>
        </dict>
        <key>10</key>
        <dict>
          <key>name</key>
          <string>constant.character.escape.linefeed.ezlanguage</string>
        </dict>
        <key>11</key>
        <dict>
          <key>name</key>
          <string>constant.character.escape.return.ezlanguage</string>
        </dict>
        <key>12</key>
        <dict>
          <key>name</key>
          <string>constant.character.escape.tab.ezlanguage</string>
        </dict>
        <key>13</key>
        <dict>
          <key>name</key>
          <string>constant.character.escape.vertical-tab.ezlanguage</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>constant.character.escape.octal.ezlanguage</string>
        </dict>
        <key>3</key>
        <dict>
          <key>name</key>
          <string>constant.character.escape.newline.ezlanguage</string>
        </dict>
        <key>4</key>
        <dict>
          <key>name</key>
          <string>constant.character.escape.backslash.ezlanguage</string>
        </dict>
        <key>5</key>
        <dict>
          <key>name</key>
          <string>constant.character.escape.double-quote.ezlanguage</string>
        </dict>
        <key>6</key>
        <dict>
          <key>name</key>
          <string>constant.character.escape.single-quote.ezlanguage</string>
        </dict>
        <key>7</key>
        <dict>
          <key>name</key>
          <string>constant.character.escape.bell.ezlanguage</string>
        </dict>
        <key>8</key>
        <dict>
          <key>name</key>
          <string>constant.character.escape.backspace.ezlanguage</string>
        </dict>
        <key>9</key>
        <dict>
          <key>name</key>
          <string>constant.character.escape.formfeed.ezlanguage</string>
        </dict>
      </dict>
      <key>match</key>
      <string>(\\x[\h]{2})|(\\[0-7]{3})|(\\\n)|(\\\\)|(\\\")|(\\')|(\\a)|(\\b)|(\\f)|(\\n)|(\\r)|(\\t)|(\\v)</string>
    </dict>
    <key>escaped_char_raw_double</key>
    <dict>
      <key>match</key>
      <string>\\"</string>
      <key>name</key>
      <string>constant.character.escape.quote.ezlanguage</string>
    </dict>
    <key>escaped_char_raw_single</key>
    <dict>
      <key>match</key>
      <string>\\'</string>
      <key>name</key>
      <string>constant.character.escape.quote.ezlanguage</string>
    </dict>
    <key>generic_names</key>
    <dict>
      <key>match</key>
      <string>[[:alpha:]_][[:alnum:]_]*</string>
      <key>name</key>
      <string>meta.identifier.ezlanguage</string>
    </dict>
    <key>generic_object_names</key>
    <dict>
      <key>match</key>
      <string>(\.\b([[:alpha:]_][[:alnum:]_]*)\b(?!\(|\[)|\b([[:alpha:]_][[:alnum:]_]*)\b\.)</string>
    </dict>
    <key>illegal_names</key>
    <dict>
      <key>comment</key>
      <string>from Lib/keyword.py, in kwlist.</string>
      <key>match</key>
      <string>(?x)
              \b (
                true | false | False | None | True | and | as | class | begin | end | do | step |
                elif | else | then | exec | for | from | global | local | if | of | program |
                import | in | is | not | or | print | return | while | with)
              \b</string>
      <key>name</key>
      <string>invalid.illegal.name.ezlanguage</string>
    </dict>
    <key>keyword_arguments</key>
    <dict>
      <key>begin</key>
      <string>\b([[:alpha:]_][[:alnum:]_]*)\s*(=)(?!=)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.function.keyword.ezlanguage</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>keyword.operator.assignment.ezlanguage</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\s*(?:(,)|(?=[\)\:]))</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.separator.parameters.ezlanguage</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
    <key>language_variables</key>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.language.ezlanguage</string>
        </dict>
      </dict>
      <key>match</key>
      <string>(?&lt;!\.)\b(self|cls)\b(?:\.|\()?</string>
    </dict>
    <key>line_continuation</key>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.separator.continuation.line.ezlanguage</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.unexpected-text.ezlanguage</string>
        </dict>
      </dict>
      <key>match</key>
      <string>(\\)(.*)$\n?</string>
    </dict>
    <key>magic_function_calls</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(?x)
                (\.)?
                \b(
                  __(?:
                  abs | and | boolean |
                  bytes | complex | contains | copy | dir | div | divmod | exit | float | floor |
                  get | hash | long | mod | new | next |
                  nonzero | or | pos | pow | set | sizeof | xor)
                __)
                \s*(?=(\())</string>
          <key>beginCaptures</key>
          <dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>support.function.magic.call.ezlanguage</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.arguments.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.arguments.end.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>meta.function-call.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>begin</key>
              <string>(?=[[:alpha:]_][[:alnum:]_]*(?:\s*\.\s*[[:alpha:]_][[:alnum:]_]*)*\s*\()</string>
              <key>end</key>
              <string>(?=\s*\()</string>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>#dotted_name</string>
                </dict>
              </array>
            </dict>
            <dict>
              <key>begin</key>
              <string>(\()</string>
              <key>beginCaptures</key>
              <dict>
                <key>1</key>
                <dict>
                  <key>name</key>
                  <string>punctuation.definition.arguments.begin.ezlanguage</string>
                </dict>
              </dict>
              <key>contentName</key>
              <string>meta.function-call.arguments.ezlanguage</string>
              <key>end</key>
              <string>(?=\))</string>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>#keyword_arguments</string>
                </dict>
                <dict>
                  <key>include</key>
                  <string>$self</string>
                </dict>
              </array>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>magic_function_names</key>
    <dict>
      <key>captures</key>
      <dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>support.function.magic.name.ezlanguage</string>
        </dict>
      </dict>
      <key>comment</key>
      <string>These methods have magic interpretation by ezlanguage and are generally
             called indirectly through syntactic constructs.</string>
      <key>match</key>
      <string>(?x)
            (procedureTODO|functionTODO|\.)?
            \s*\b(
              __(?:
                abs | and | boolean |
                bytes | complex | contains | copy | dir | div | divmod | exit | float | floor |
                get | hash | long | mod | new | next |
                nonzero | or | pos | pow | set | sizeof | xor)
            __)
            \b</string>
    </dict>
    <key>magic_variable_names</key>
    <dict>
      <key>captures</key>
      <dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>support.variable.magic.ezlanguage</string>
        </dict>
      </dict>
      <key>comment</key>
      <string>magic attributes which a class/module may have.</string>
      <key>match</key>
      <string>(?x)
            (\.)?
            \b(
              __(?:
              annotations | class | code | debug | doc | file )
            __) \b</string>
    </dict>
    <key>regular_expressions</key>
    <dict>
      <key>comment</key>
      <string>Changed disabled to 1 to turn off syntax highlighting in “r” strings.</string>
      <key>disabled</key>
      <integer>0</integer>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>source.regexp.ezlanguage</string>
        </dict>
      </array>
    </dict>
    <key>string_quoted_double</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>([uU]r)(""")</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.string.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>single quoted unicode-raw string</string>
          <key>end</key>
          <string>"""</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.block.unicode-raw-regex.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#constant_placeholder</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_char_raw_double</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#regular_expressions</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>([uU]R)(""")</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.string.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>single quoted unicode-raw string without regular expression highlighting</string>
          <key>end</key>
          <string>"""</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.block.unicode-raw.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#constant_placeholder</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_char_raw_double</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>([bB]r)(""")</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.string.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>single quoted bytes-raw string</string>
          <key>end</key>
          <string>"""</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.block.bytes-raw-regex.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#constant_placeholder</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_char_raw_double</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#regular_expressions</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>([bB]R)(""")</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.string.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>single quoted bytes-raw string without regular expression highlighting</string>
          <key>end</key>
          <string>"""</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.block.bytes-raw.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#constant_placeholder</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_char_raw_double</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(r)(""")</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.string.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>double quoted raw string</string>
          <key>end</key>
          <string>"""</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.block.raw-regex.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#constant_placeholder</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_char_raw_double</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#regular_expressions</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(R)(""")</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.string.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>double quoted raw string</string>
          <key>end</key>
          <string>"""</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.block.raw.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#constant_placeholder</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_char_raw_double</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>([uU])(""")</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.string.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>double quoted unicode string</string>
          <key>end</key>
          <string>"""</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.block.unicode.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#constant_placeholder</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_unicode_char</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_char</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>([bB])(""")</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.string.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>double quoted bytes string</string>
          <key>end</key>
          <string>"""</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.block.bytes.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#constant_placeholder</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_unicode_char</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_char</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.string.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
            <key>3</key>
            <dict>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>#constant_placeholder</string>
                </dict>
                <dict>
                  <key>include</key>
                  <string>#escaped_char_raw_double</string>
                </dict>
                <dict>
                  <key>include</key>
                  <string>#regular_expressions</string>
                </dict>
              </array>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>double-quoted raw string</string>
          <key>match</key>
          <string>([uU]r)(")((?:[^"\\]|\\.)*)(")</string>
          <key>name</key>
          <string>string.quoted.double.single-line.unicode-raw-regex.ezlanguage</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>([uU]R)(")</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.string.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>double-quoted raw string</string>
          <key>end</key>
          <string>(")|(\n)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal.unclosed-string.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.single-line.unicode-raw.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#constant_placeholder</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_char_raw_double</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>([bB]r)(")</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.string.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>double-quoted raw string</string>
          <key>end</key>
          <string>(")|(\n)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal.unclosed-string.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.single-line.bytes-raw-regex.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#constant_placeholder</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_char_raw_double</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#regular_expressions</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>([bB]R)(")</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.string.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>double-quoted raw string</string>
          <key>end</key>
          <string>(")|(\n)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal.unclosed-string.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.single-line.bytes-raw.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#constant_placeholder</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_char_raw_double</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.string.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
            <key>3</key>
            <dict>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>#constant_placeholder</string>
                </dict>
                <dict>
                  <key>include</key>
                  <string>#escaped_char_raw_double</string>
                </dict>
                <dict>
                  <key>include</key>
                  <string>#regular_expressions</string>
                </dict>
              </array>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>double-quoted raw string</string>
          <key>match</key>
          <string>(r)(")((?:[^"\\]|\\.)*)(")</string>
          <key>name</key>
          <string>string.quoted.double.single-line.raw-regex.ezlanguage</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(R)(")</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.string.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>double-quoted raw string</string>
          <key>end</key>
          <string>(")|(\n)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal.unclosed-string.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.single-line.raw.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#constant_placeholder</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_char_raw_double</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>([uU])(")</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.string.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>double quoted unicode string</string>
          <key>end</key>
          <string>(")|(\n)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal.unclosed-string.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.single-line.unicode.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#constant_placeholder</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_unicode_char</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_char</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>([bB])(")</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.string.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>double quoted bytes string</string>
          <key>end</key>
          <string>(")|(\n)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal.unclosed-string.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.single-line.bytes.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#constant_placeholder</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_unicode_char</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_char</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(""")(?=\s*(SELECT|INSERT|UPDATE|DELETE|CREATE|REPLACE|ALTER))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>double quoted string</string>
          <key>end</key>
          <string>"""</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.block.sql.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#constant_placeholder</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_unicode_char</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_char</string>
            </dict>
            <dict>
              <key>include</key>
              <string>source.sql</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(")(?=\s*(SELECT|INSERT|UPDATE|DELETE|CREATE|REPLACE|ALTER))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>double quoted string</string>
          <key>end</key>
          <string>(")|(\n)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal.unclosed-string.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.single-line.sql.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>captures</key>
              <dict>
                <key>0</key>
                <dict>
                  <key>patterns</key>
                  <array>
                    <dict>
                      <key>include</key>
                      <string>#constant_placeholder</string>
                    </dict>
                    <dict>
                      <key>include</key>
                      <string>#escaped_unicode_char</string>
                    </dict>
                    <dict>
                      <key>include</key>
                      <string>#escaped_char</string>
                    </dict>
                    <dict>
                      <key>include</key>
                      <string>source.sql</string>
                    </dict>
                  </array>
                </dict>
              </dict>
              <key>match</key>
              <string>(\G|^)([^"\\]|\\.)*(?="|$)</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(""")</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>double quoted string</string>
          <key>end</key>
          <string>"""</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.block.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#constant_placeholder</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_unicode_char</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_char</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(")</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ezlanguage</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>double quoted string</string>
          <key>end</key>
          <string>(")|(\n)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ezlanguage</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal.unclosed-string.ezlanguage</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.single-line.ezlanguage</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#constant_placeholder</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_unicode_char</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#escaped_char</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>strings</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#string_quoted_double</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#string_quoted_single</string>
        </dict>
      </array>
    </dict>
  </dict>
  <key>scopeName</key>
  <string>source.ezlanguage</string>
  <key>uuid</key>
  <string>G43DB5B2-7D08-11D9-A709-000D93B6E43C</string>
</dict>
</plist>