language: cpp
sudo: required
dist: trusty
cache: apt

notifications:
  # slack: ezlanguage:Lx6iO5M1QzE01l4om91A36fo
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c8aafc19661a5dc78922
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

os:
  - linux
  
addons:
  apt:
    sources:
      # gcc/g++ repository
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

install:
# g++ install
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-4.9"; fi
  - alias g++="g++-5"
  - g++ --version
  - echo -e "================="
  - $CXX --version

script:
  - make --file makefile -j2
  - ./bin/EZ_language_compiler tests/example.ezl
# Launch valid tests
  - cd tests/
  - bash basic_tests.sh

after_success:
# Launch other tests
  - bash full_tests.sh
  - cd ../examples
  - bash valid_tests.sh
  - bash unvalid_tests.sh

