%{
#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <list>
#include <string>
#include <vector>
#include <cstdarg>

#include "../src/global.h"	 // we start from ../obj because it's important
#include "../src/hash_table/FunctionHashed.h"
#include "../src/hash_table/ScopeHashTable.h"
#include "../src/hash_table/VariableHashed.h"
#include "../src/main.cpp"	 // we start from ../obj because it's important
#include "../src/declarations/Class.h"
#include "../src/declarations/Function.h"
#include "../src/declarations/Procedure.h"
#include "../src/declarations/Variable.h"
#include "../src/modules/Node.h"
#include "../src/modules/Program.h" // Empty Node

#include "../src/global.h"


bool existing_parsing_error= false;

extern FILE* yyin;
using namespace std;

int yyparse (void);
extern "C" int yylex();
// extern YYLTYPE yylloc;
// extern "C" void yyerror(const char *s, ...);
extern "C" void yyerror(const std::string&);
extern "C" void yyprint(const std::string&);
extern int yylineno;

// Return the string value without quotation_marks
string delete_quote(string & str ){
  return str.substr(1,str.size()-2);
}

// Returns the argument value
string get_argument_value(string & str ){
  return str.substr(str.find_last_of("-")+1,str.size()-4);
}

extern ScopeHashTable symbolTable;

/* handle locations */
int yycolumn = 1;

#define YY_USER_ACTION yylloc.first_line = yyloc.last_line = yylineno; \
    yylloc.first_column = yycolumn; yylloc.last_column = yycolumn+yyleng-1; \
    yycolumn += yyleng;

#define YYERROR_VERBOSE
#define YY_USER_INIT yylloc.first_line=1;
#define USE(VALUE) /*empty*/  

%}


// Tokens
%token<texte>	NUM_INTEGER     // Integer
%token<texte>	NUM_REAL			  // Real
%token<texte> NAME RETOUR STRING STRING_PARAM
%token COMMA DEGRE POURCENT DIESE POINT QUOTE		// Caractères
%token<texte> TYPE_INTEGER TYPE_REAL TYPE_STRING TYPE_BOOLEAN     // variables typeVar
%token EGAL NE LT LE GT GE PLUS MINUS MULT DIVISE
%token  LEFT_PARENTHESIS RIGHT_PARENTHESIS LEFT_ACCOLADE RIGHT_ACCOLADE LEFT_BRACKET RIGHT_BRACKET FIN BACK_LINE	// Special Characters
%token<texte> CONST VARIABLE SHARED LOCAL GLOBAL IS ARE           // variables declaration
%token IMPORT INCLUDE LIBRARY EXTERN						                  // module import - c++ code
%token IF THEN ELSE   						  // if else 
%token WHEN CASE DEFAULT ENDWHEN	  // switch case ...
%token WHILE ENDWHILE							  // while .. do ...
%token REPEAT UNTIL ENDREPEAT 			// do .. while ...
%token FOR IN DO STEP 
%token FUNCTION PROCEDURE RETURNS RETURN	 	// functions
%token PRINT
%token BEGINN END						        // can not use 'BEGIN'
%token END_OF_FILE
%token CLASS PROGRAM DESTRUCT			  //class
%token ARGUMENTS AS							    // arguments	
%token REGEX SEARCH MATCH 					// Regular expression

%token LENGTH TOUPPERCASE TOLOWERCASE
%token SUBSTRING SPLIT STRIP
%token REPLACE CONTAINS
%token FIND FINDFIRSTOF FINDLASTOF

%token ARRAY VECTOR LIST SET MAP OF

%token SIZE IS_EMPTY CLEAR FILL
%token RANDOMIZE COUNT MAX MIN SORT
%token SUM REMOVE RANGE PUT_FIRST PUT_LAST
%token REMOVE_LAST REMOVE_FIRST AVERAGE STORE
%token RESTORE FIRST LAST REMOVE_AT
%token PUT_AT INSERT EXIST

%left PLUS MINUS EGAL
%left NE LT LE GT GE MULT DIVISE AND OR XOR NOT MOD POW ABS OPERATOR		// Operators

%type<texte> type operators portee string designator
%type<arbre> statement_sequence function_call affect declaration statement
%type<arbre> next_line function procedure class return 
%type<arbre> ROOT imports declaration_arguments declaration_classes declarations_list declaration_variables declaration_methods variable_with_scope variable_without_scope
%type<arbre> function_string map_declaration array_declaration vector_declaration list_declaration set_declaration
%type<vecString> list_arguments
%type<texte> expression single_expression names nbrOrName params param_args param_type
%type<texte> forDecl forType forRange forStep forBody returnstype procedureDecl

// Parameters
// %define parse.trace

%start ROOT
%%

ROOT:
  PROGRAM NAME next_line imports declaration_arguments declaration_classes declarations_list PROCEDURE NAME statement_sequence END endprocedure END_OF_FILE
	{
		Node* p_imports = $4;
		Program *racine = new Program(p_imports, $2);
    /* TODO add program arguments logic */
		Node* p_decl_class = $6;
		Node* p_decl_list = $7;
    
    Node* p_args = $5;
		Node* p_prog = $10;
    // Function* main= new Function(p_prog, nullptr, $9, p_args, "int");

    p_imports->setRightSon(p_args);
    p_args->setRightSon(p_decl_class);
		p_decl_class->setRightSon(p_decl_list);
		// p_decl_list->setRightSon(main);

		cout << racine->translate() << endl;
    /* TODO program translation save */
		return 0;
	}
;

/* ******************
 *  PROGRAM MODULES *
 * ******************/

// import modules or libraries
imports:
  /* empty */
| imports import { debug("import;", AT); /* TODO import logic */ }
;

declaration_arguments:
  /* empty */
| ARGUMENTS next_line param_args END endargument next_line {
    /* TODO arguements declaration logic */
    debug("arguments declaration;", AT);
  }
;

declaration_classes:
  /* empty */
| declaration_classes class next_line
	{
		Class* c = (Class *) $1;
    debug("class declared : " + c->getName()+":", AT);
		$1->setRightSon($2);
		$$ = c;
	}
;

declarations_list:
  declaration_variables declaration_methods
    {
      // PDVariables* vars = (PDVariables*) $1;
      // PDFunctions* functs = (PDFunctions*) $2;
      Node* vars=  $1;
      Node* functs = $2;
      $1->setRightSon(functs);
      $$ = vars;
    }
  | declaration_methods declaration_variables
    {
      // PDVariables* vars = (PDVariables*) $1;
      // PDFunctions* functs = (PDFunctions*) $2;
      Node* functs = $1;
      Node* vars= $2;
      $1->setRightSon(vars);
      $$ = vars;
    }
;

declaration_variables:
/* empty */ { $$ = NULL;}
| variable_with_scope declaration_variables
	{
	}
| variable_without_scope declaration_variables
	{
	  /* $$ = new Variable(); */
	}
;
/* ******************
 *    SUBMODULES    *
 * ******************/

/* imports */
import:
  IMPORT NAME next_line {
    /* TODO import logic (name of module) */
    cout << "importation du module " << $2 << endl;
  }
| INCLUDE string next_line {
    /* TODO include import logic */
    cout << " inclusion de la bibliothèque " << delete_quote($2) << endl ;
  }
| LIBRARY string next_line {
    /* TODO library import logic */
    cout << " inclusion de la LIBRARY " << delete_quote($2) << endl ;
  }
;

/* declaration_arguments */
param_args:
    NAME IS param_type AS STRING_PARAM next_line { cout << "parameter " << get_argument_value($5) << endl;} // ex: x is integer as "--x"
| NAME IS param_type AS STRING_PARAM next_line param_args { cout << "paramètre " << get_argument_value($5) << endl; }
;

// Past arguments should be of only one of the following types: 
param_type:
  TYPE_INTEGER  { $$ = $1; }
| TYPE_REAL     { $$ = $1; } 
| TYPE_STRING   { $$ = $1; } 
;

/* declaration_classes */
class:
  CLASS NAME next_line begin statement_sequence END endclass
	{
    /* TODO class declaration logic */
		$$ = new Class();
		cout << "class declaration " << $2 << endl;
	}
;

/* ********************
 *  GENERIC RECURSIVE *
 * ********************/

statement_sequence:
  /* empty */ { cout<< "last statement"<< endl; /* $$ = new Variable(); */ }
| statement_sequence statement { }
;

names:
  NAME              { $$ = $1; }
| names COMMA NAME  { $$ = $1 + ", " + $3; }
;

/* ******************
 *    METHODS    *
 * ******************/

/* declaration_methods */
declaration_methods:
  /* empty */ { $$ = NULL;}
| declaration_methods function next_line
	{
		Function* f = (Function*) $2;
		f->setLeftSon($1);
		$$ = f;
	}
| declaration_methods procedure next_line
	{
		Procedure* p = (Procedure*) $2;
		p->setLeftSon($1);
		$$ = p;
	}
;

returnstype:
  RETURNS type
  {
    // $$= new Type($2);
  }
;

return:
  RETURN expression
  {
    // $$= new Return($2);
  }
;

function:
  SHARED FUNCTION NAME LEFT_PARENTHESIS list_arguments // {symbolTable.incScope(); }
  RIGHT_PARENTHESIS returnstype next_line begin statement_sequence return next_line END endfunction
	{
    /* TODO function declaration logic 1 */
		cout << "declaration de la fonction " << $3 << endl;
	}
| FUNCTION NAME LEFT_PARENTHESIS list_arguments // { symbolTable.incScope(); }
  RIGHT_PARENTHESIS returnstype next_line begin statement_sequence return next_line END endfunction {
    cout << "declaration de la fonction" << $2 << endl;
    // Right son of last instruction is return statement
    $9->setRightSon($10);
		Function *f = new Function($9, nullptr, $2,$4,$6);
		$$ = f;
		//$$ = new Variable();
		symbolTable.decScope();
	}
| FUNCTION NAME LEFT_PARENTHESIS list_arguments RIGHT_PARENTHESIS IS EXTERN NAME {
  /* TODO function declaration logic 3 */
    cout << "declaration d'une fonction externe " << endl;
  }
;

procedureDecl:
  PROCEDURE NAME LEFT_PARENTHESIS list_arguments RIGHT_PARENTHESIS
  {
    cout << "Déclaration de la procedure " << $2 << endl;
    symbolTable.incScope();
  }
| PROCEDURE NAME
  {
    cout << "Déclaration de la procedure " << $2 << endl;
    symbolTable.incScope();
  }
;

procedure:
  procedureDecl next_line statement_sequence END endprocedure
  {
    /* TODO procedure declaration logic 1 */
    // Procedure *f = new Procedure($1,$4,$4);
		$$ = nullptr; // = f
		symbolTable.decScope();
  }
| PROCEDURE PRINT LEFT_PARENTHESIS  RIGHT_PARENTHESIS next_line begin statement_sequence END endprocedure {
    /* TODO print overloading logic 1 */
    cout << "Surcharge de la methode d'affichage \"print\" "  << endl;
  }
| SHARED PROCEDURE NAME LEFT_PARENTHESIS list_arguments RIGHT_PARENTHESIS next_line begin  statement_sequence END endprocedure {
  /* TODO procedure declaration logic 2 */
    cout << "Déclaration de la procedure " << $3 << endl;
  }
| SHARED PROCEDURE PRINT LEFT_PARENTHESIS  RIGHT_PARENTHESIS next_line begin statement_sequence END endprocedure {
    /* TODO print overloading logic 2 (factorize) */
    cout << "Surcharge de la methode d'affichage \"print\" "  << endl;
  }
;

/* ******************
 *   INSTRUCTIONS   *
 * ******************/

statement:
  next_line {}
| variable_with_scope   {} 
| variable_constant     {}
| variable_without_scope next_line  { }
| affectation next_line             { } 
| function_call next_line           { }
| declaration { $$ = $1; }
;

declaration:
  map_declaration     { $$ = $1; }
| array_declaration   { $$ = $1; }
| vector_declaration  { $$ = $1; }
| list_declaration    { $$ = $1; }
| set_declaration     { $$ = $1; }
;

statement:
  next_line
| variable_with_scope               { }
| variable_without_scope next_line  { }
| affectation next_line             { } 
| function_call next_line           { }
| declaration_methods {}
| destruct {}
| printing {}
| overloading {}
| if          {}
| when        {}
| while       {}
| repeat      {}
| for         {}
;

/* ************************
 *  Complex Instructions  *
 * ************************/
function_call:
  NAME POINT simple_function {}
| function_call POINT simple_function {}
| simple_function { }
| NAME POINT NAME { }  
| function_string { $$ = $1;}
| function_regex { }
| containers_methods { }
;

simple_function:
  // function without parameter
  NAME LEFT_PARENTHESIS RIGHT_PARENTHESIS {} 
  // function with parameter
| NAME LEFT_PARENTHESIS params RIGHT_PARENTHESIS {} 
;

if:
  IF expression THEN next_line statement_sequence  END endif {
    /* TODO if-then logic */
    printf("SI   ALORS \n");
  }
| IF expression THEN next_line statement_sequence ELSE next_line statement_sequence END endif {
    /* TODO if-else-then logic */
    printf("SI_SINON_ALORS \n");
  }
;

when:
  WHEN expression IS next_line whenbody whendefault END endwhen {
    /* TODO when logic */
    printf("when .. case .. \n");
  }
;

whenbody: /* whenbody can't be empty */
  CASE expression next_line statement_sequence END endcase next_line {
    /* TODO whenbody logic 1 */
    cout << "case body" << endl;
  }
| CASE expression next_line statement_sequence END endcase next_line whenbody {
    /* TODO whenbody logic 2 */
    cout << "case body" << endl;
  }
;

whendefault: /* May not be specified */
  /* empty */
| DEFAULT next_line statement_sequence END endcase next_line {
    /* TODO whendefault logic 1 */
  }
;

while:
  WHILE expression DO statement_sequence END endwhile {
    /* TODO while logic */
    printf("WHILE .. DO .. \n");
  }
;

repeat:
  REPEAT statement_sequence UNTIL next_line expression next_line END endrepeat {
    /* TODO repeat-until logic */
    printf("REPEAT .. UNTIL .. \n");
  }
;

/* for */
forDecl:
  FOR NAME { $$= $2; }
;

forType:
  IS type { $$= $2; }
;

forRange:
  IN expression doublepoint expression { 
    /* TODO for range logic */
  }
;

forStep: // @see do step should be text or real_value
  STEP nbrOrName { $$= $2; }
;

forBody:
  DO next_line statement_sequence END endfor next_line { 
    /* TODO for body logic */
  }
;

for:
  forDecl forRange forBody {
    /* TODO 'for a in b .. c' logic */
    printf("FOR .. IN ... \n");
  }
| forDecl forRange forStep forBody {
    /* TODO 'for a in b .. c step x' logic */
    printf("FOR .. IN ... \n");
  }
| forDecl forType forRange forBody {
    /* TODO 'for a is TYPE in b .. c' logic */
    printf("FOR a IN b .. c\n");
  }
| forDecl forType forRange forStep forBody {
    /* TODO 'for a is TYPE in b .. c step x' logic */
    printf("FOR a is TYPE IN b .. c STEP x\n");
  }
;

/* ************************
 *   Simple Instructions  *
 * ************************/
affectation:
  NAME EGAL expression { cout << "Affectation name " <<  endl; }
| NAME POINT NAME EGAL expression { cout << "Affectation name.name " <<  endl; }
| NAME PLUS PLUS { cout << "Affectation ++" <<  endl; }
| NAME MINUS MINUS {  cout << "Affectation --" <<  endl; }
| PLUS PLUS NAME  { cout << "++ Affectation " <<  endl; }
| MINUS MINUS NAME  { cout << "-- Affectation " <<  endl;  }
;

destruct:
  // TODO reword destruction definition
  DESTRUCT next_line statement_sequence END enddestruct {
    /* TODO destructions logic */
    cout << "destructeur " << endl;
  }
;

printing:
PRINT expressions next_line {
    /* TODO overloading logic */
  }
;

overloading:
  OPERATOR operators LEFT_PARENTHESIS NAME IS NAME RIGHT_PARENTHESIS RETURN type next_line statement_sequence END {
    /* TODO overloading logic */
    cout << "operateur " <<  $2 << endl;
  }
;

/* *******************
 *  GENERIC COMPLEX  *
 * ******************/

// one or several new lines
next_line:
  BACK_LINE /* Nothing to do */
| next_line BACK_LINE /* Nothing to do */
;

list_arguments:
  /* empty */ {
    vector<VariableHashed> v;
    $$ = v;
  }
| NAME IS type
 	{
 		vector<VariableHashed> v;
 		v.push_back(VariableHashed($1,$3));
 		$$ = v;
 	}
| NAME IS type COMMA list_arguments
 	{
 		$5.push_back(VariableHashed($1,$3));
 		$$ = $5;
 	}
| NAME names ARE type { /* todo list_arguments logic */ }
;

variable_without_scope:
  NAME IS type affect
	{
    cout << "Déclaration de la variable1 " << $1 << endl;
		VariableHashed v($1,$3);
		symbolTable.addElement(v);
		$$ = new Variable(nullptr, nullptr, $1,$3,"",$4,false);
	}
| NAME names ARE type affect
	{
		cout << "Variable des variables1 "<< $1 << endl;
	}
| NAME IS SHARED type affect
	{
		cout << "Variable de la variable1 " << $1 << endl;
	}
| NAME names ARE SHARED type affect
	{
		cout << "Variable des variables1 "<< $1 << endl;
	}
| variable_construct
  {
    /* TODO variable construction logic (with class) */
    cout << "variable construction (class)" << endl ;
  } 
;

variable_with_scope:
  portee NAME IS type affect next_line
  	{
  		VariableHashed v($2,$4);
  		symbolTable.addElement(v);
  		// $$ = new Variable($2,$4,$1,false);
  	}
| portee NAME names ARE type next_line
	{
		cout << "  list_arguments des variables  avec portee "<< $2 << endl;
	}
| portee NAME IS SHARED type affect next_line
	{
		VariableHashed v($2,$4);
		symbolTable.addElement(v);
		// $$ = new Variable($2,$4,$1,true);
	}
| portee NAME names ARE SHARED type next_line
	{
		cout << "  Variable des variables  avec portee "<< $2 << endl;
	}

variable_constant:
  CONST NAME IS  type affect  { cout << "Déclaration de la variable constante " << $1 << endl; }
| CONST NAME names ARE  type affect  { cout << "Déclaration des variables constante "<< $1 << endl; }
| CONST NAME IS SHARED type affect  { cout << "Déclaration de la variable constante " << $1 << endl; }
| CONST NAME names ARE SHARED type affect  { cout << "Déclaration des variables constante "<< $1 << endl; }
;

variable_construct:
  NAME IS NAME {}  // ex: c is Maclasse
| NAME IS NAME LEFT_PARENTHESIS class_liste_argument RIGHT_PARENTHESIS {} // c is MaClass(val1,va2)
| NAME IS NAME LEFT_PARENTHESIS class_liste_argument_with_assignment RIGHT_PARENTHESIS {} // p is Person(name="name")
;

expression:
  /* TODO expressions logic */
  expression EGAL EGAL expression { /* $$ = new Variable(); */ }
| expression NE expression {/* $$ = new Variable(); */ }
| expression LT expression { /* $$ = new Variable(); */ }
| expression LE expression { /* $$ = new Variable(); */ }
| expression GT expression {/* $$ = new Variable(); */ }
| expression GE expression { /* $$ = new Variable(); */ }
| expression PLUS expression {/* $$ = new Variable(); */ }
| expression MINUS expression { /* $$ = new Variable(); */ }
| expression MULT expression {/* $$ = new Variable(); */ }
| expression DIVISE expression {/* $$ = new Variable(); */ }
| expression AND AND expression { /* $$ = new Variable(); */ }
| expression OR OR expression {/* $$ = new Variable(); */ }
| single_expression { yyprint("single_expression");  /* $$ = new Variable(); */ /* $1 = $1 */ }
;

expressions:
  expression  { cout <<"affichage  : " <<  $1  << endl; }
| string      { cout << "affichage  : " << delete_quote($1) << endl; }
| expression COMMA expressions  { cout <<"affichage  : " <<  $1 << endl; }
| string COMMA expressions      {   cout << "affichage : " << delete_quote($1) << endl; }
;

params:
  expression { $$ = $1;}
| expression COMMA params { $$ = $1 ;}
;

single_expression:
  /* single_expressions logic */
  PLUS single_expression { /* $$ = new Variable(); */ }
| single_expression XOR single_expression { /* $$ = new Variable(); */ }
| NOT single_expression { /* $$ = new Variable(); */ }
| single_expression MOD single_expression { /* $$ = new Variable(); */ }
| single_expression POW single_expression { /* $$ = new Variable(); */ }
| ABS single_expression { /* $$ = new Variable(); */ }
| LEFT_PARENTHESIS expression RIGHT_PARENTHESIS { /* $$ = new Variable(); */ }
| NUM_REAL { $$ = $1; } //real
| NUM_INTEGER { $$ = $1; }  // integer /* TODO ADD litteral creation */
| designator { /* $$ = String($1); */ }
;

/* ******************
 *  GENERIC SIMPLE  *
 * ******************/

doublepoint:
 POINT POINT
;

begin:
  /* empty */
| BEGINN next_line { }
;

affect:
  /* empty */
| EGAL expression { }
| EGAL string { }
;

class_liste_argument:
  string { }
| NUM_INTEGER  {}
| NUM_REAL  {}
| NAME  {}
| string COMMA class_liste_argument  { }
| NUM_INTEGER COMMA class_liste_argument  {}
| NUM_REAL COMMA class_liste_argument  {}
| NAME COMMA class_liste_argument {}
;

class_liste_argument_with_assignment:
  NAME EGAL string { }
| NAME EGAL NUM_INTEGER   {}
| NAME EGAL NUM_REAL  {}
| NAME EGAL NAME  {}
| NAME EGAL string COMMA class_liste_argument_with_assignment  { }
| NAME EGAL NUM_INTEGER COMMA class_liste_argument_with_assignment  {}
| NAME EGAL NUM_REAL COMMA class_liste_argument_with_assignment  {}
| NAME EGAL NAME COMMA class_liste_argument_with_assignment {}
;

operators:
  EGAL EGAL { $$ = "==";}
| EGAL   { $$ = "=";}
| NE  { $$= "!="; }
| LT  { $$ =  "<"; }
| LE  { $$ = "<=";}
| GT  { $$ = ">";}
| GE  { $$ = ">=";}
| PLUS   {$$ ="+";}
| MINUS  { $$ = "-";}
| MULT   {$$ = "*";}
| DIVISE { $$ =  "/";}
;

nbrOrName:
  NUM_INTEGER { /* $$ = Integer(to_string($1)); */ }
| NUM_REAL    { /* $$ = Real($1); */ }
| NAME        { /* $$ = String($1); */ }
;

portee: 
 LOCAL    { $$ = "local";}
| GLOBAL  { $$ = "global";}
;

type:
  TYPE_INTEGER  { $$ = "int";}
| TYPE_REAL     { $$ = "real";}
| TYPE_STRING   { $$ = "string";}
| TYPE_BOOLEAN  { $$ = "bool";}
;

string :
 STRING  { $$= $1;}
;

designator:
  NAME { 
    $$=$1;
  }
;

string:
  STRING  { $$ = $1; }
;

strOrName:
  string { }
| NAME { } 
;

/* *********************
 * FACULATIVE END TAGS *
 * *********************/

endclass:
  /* empty */
| CLASS {}
;

endfunction:
  /* empty */
| FUNCTION {}
;

endprocedure:
  /* empty */
| PROCEDURE {}
;

endif:
  /* empty */
| IF {}
;

endwhen:
  /* empty */
| WHEN  {}
;

endcase:
  /* empty */
| CASE {}
;

endwhile:
  /* empty */
| WHILE {}
;

endfor:
  /* empty */
| FOR {}
;

endrepeat:
  /* empty */
| REPEAT {}
;

enddestruct:
  /* empty */
| DESTRUCT {}
;

endargument:
  /* empty */
| ARGUMENTS {}
;


/* ************
 *    OTHER   *
 * ************/
// 		---------------------------------------------------------------------
// 		---------------------------------------------------------------------

/* else_body:
   ELSE next_line statement_sequence   { cout << "else " << endl; }
|  ELSE next_line statement_sequence  else_body  { cout << "else " << endl;}
;*/

//    -----------------------------REGEX METHODS-----------------------------------------
function_regex:
  NAME POINT MATCH LEFT_PARENTHESIS strOrName RIGHT_PARENTHESIS { cout << "regular expression MATCH " << endl ;}
| NAME POINT SEARCH LEFT_PARENTHESIS strOrName COMMA strOrName RIGHT_PARENTHESIS { cout << "regular expression SEARCH " << endl ;}
| NAME POINT REPLACE LEFT_PARENTHESIS strOrName COMMA strOrName RIGHT_PARENTHESIS { cout << "regular expression REPLACE " << endl ;}
;

//    -----------------------------STRING METHODS----------------------------------------
function_string: 
  NAME POINT LENGTH LEFT_PARENTHESIS RIGHT_PARENTHESIS { printf("lENGTH() called \n"); }
| NAME POINT TOUPPERCASE LEFT_PARENTHESIS RIGHT_PARENTHESIS { printf("toUpperCase() called \n"); }
| NAME POINT TOLOWERCASE LEFT_PARENTHESIS RIGHT_PARENTHESIS { printf("toLowerCase() called \n"); }
| NAME POINT SUBSTRING LEFT_PARENTHESIS NUM_INTEGER RIGHT_PARENTHESIS { printf("SUBSTRING(int) called \n"); }
| NAME POINT SUBSTRING LEFT_PARENTHESIS NAME RIGHT_PARENTHESIS { printf("SUBSTRING(int) called \n"); }
| NAME POINT SUBSTRING LEFT_PARENTHESIS NUM_INTEGER COMMA NUM_INTEGER RIGHT_PARENTHESIS { printf("SUBSTRING(int,int) called \n"); }
| NAME POINT SUBSTRING LEFT_PARENTHESIS NAME COMMA NUM_INTEGER RIGHT_PARENTHESIS { printf("SUBSTRING(int,int) called \n"); }
| NAME POINT SUBSTRING LEFT_PARENTHESIS NUM_INTEGER COMMA NAME RIGHT_PARENTHESIS { printf("SUBSTRING(int,int) called \n"); }
| NAME POINT SUBSTRING LEFT_PARENTHESIS NAME COMMA NAME RIGHT_PARENTHESIS { printf("SUBSTRING(int,int) called \n"); }
| NAME POINT SPLIT LEFT_PARENTHESIS STRING RIGHT_PARENTHESIS { printf("SPLIT(\"str\") called \n"); }
| NAME POINT STRIP LEFT_PARENTHESIS RIGHT_PARENTHESIS { printf("strip() called \n"); }
| NAME POINT STRIP LEFT_PARENTHESIS STRING RIGHT_PARENTHESIS { printf("strip(\"str\") called \n"); }
| NAME POINT REPLACE LEFT_PARENTHESIS STRING COMMA STRING RIGHT_PARENTHESIS { printf("replace(\"str\",\"str\") called \n"); }
| NAME POINT CONTAINS LEFT_PARENTHESIS STRING RIGHT_PARENTHESIS { printf("contain(\"str\") called \n"); }
| NAME POINT FIND LEFT_PARENTHESIS STRING RIGHT_PARENTHESIS { printf("find(\"str\") called \n"); }
| NAME POINT FINDFIRSTOF LEFT_PARENTHESIS STRING RIGHT_PARENTHESIS { printf("findFirstOF(\"str\") called \n"); }
| NAME POINT FINDLASTOF LEFT_PARENTHESIS STRING RIGHT_PARENTHESIS { printf("findFirstOF(\"str\") called \n"); }
;


//    -----------------------------array Déclaration----------------------------------------
array_declaration:
portee NAME IS ARRAY LEFT_BRACKET NUM_INTEGER POINT POINT NUM_INTEGER RIGHT_BRACKET OF type { printf("array declaration with lower and upper bound \n"); }
| portee NAME IS ARRAY LEFT_BRACKET NUM_INTEGER POINT POINT NAME RIGHT_BRACKET OF type { printf("array declaration with lower and upper bound \n"); }
| portee NAME IS ARRAY LEFT_BRACKET NAME POINT POINT NUM_INTEGER RIGHT_BRACKET OF type { printf("array declaration with lower and upper bound\n"); }
| portee NAME IS ARRAY LEFT_BRACKET NUM_INTEGER RIGHT_BRACKET OF type { printf("array declaration with size \n"); }
| portee NAME IS ARRAY LEFT_BRACKET NAME RIGHT_BRACKET OF type { printf("array declaration with size \n"); }
| portee NAME IS ARRAY LEFT_BRACKET NUM_INTEGER RIGHT_BRACKET OF type EGAL LEFT_ACCOLADE names RIGHT_ACCOLADE { printf("array declaration  with initializer list \n"); }
| portee NAME IS ARRAY LEFT_BRACKET NAME RIGHT_BRACKET OF type EGAL LEFT_ACCOLADE names RIGHT_ACCOLADE { printf("array declaration with size with initializer list \n"); }
;

//    -----------------------------vector declaration----------------------------------------
vector_declaration: 
portee NAME IS VECTOR OF type { printf("vector declaration  \n"); }
| portee NAME IS VECTOR LEFT_BRACKET NUM_INTEGER RIGHT_BRACKET OF type { printf("vector declaration with size \n"); }
| portee NAME IS VECTOR LEFT_BRACKET NAME RIGHT_BRACKET OF type { printf("vector declaration with size \n"); }
| portee NAME IS VECTOR OF type EGAL LEFT_ACCOLADE names RIGHT_ACCOLADE { printf("vector declaration with initializer list \n"); }
;

//    -----------------------------list declaration----------------------------------------
list_declaration: 
portee NAME IS LIST OF type { printf("list declaration  \n"); }
| portee NAME IS LIST OF type EGAL LEFT_ACCOLADE names RIGHT_ACCOLADE { printf("list declaration with initializer list \n"); }
;

//    -----------------------------set declaration----------------------------------------
set_declaration: 
portee NAME IS SET OF type { printf("set declaration  \n"); }
| portee NAME IS SET LEFT_BRACKET NUM_INTEGER RIGHT_BRACKET OF type { printf("set declaration with size \n"); }
| portee NAME IS SET LEFT_BRACKET NAME RIGHT_BRACKET OF type { printf("set declaration with size \n"); }
| portee NAME IS SET OF type EGAL LEFT_ACCOLADE names RIGHT_ACCOLADE { printf("set declaration with initializer list \n"); }
;

//    -----------------------------map declaration----------------------------------------
map_declaration: 
portee NAME IS MAP OF LT type COMMA type GT { printf("map declaration  \n"); }
| map_declaration EGAL LEFT_ACCOLADE names RIGHT_ACCOLADE { printf("map declaration with initializer list \n"); }
;

//    ---------------------------------------------------------------------------------------
//    -----------------------------Containers methods---------------------------------------
//    ---------------------------------------------------------------------------------------

containers_methods : 
NAME POINT SIZE LEFT_PARENTHESIS RIGHT_PARENTHESIS        { printf("utilisation de la méthode size  \n"); }
| NAME POINT IS_EMPTY LEFT_PARENTHESIS RIGHT_PARENTHESIS  { printf("utilisation de la méthode size  \n"); }
| NAME POINT CLEAR LEFT_PARENTHESIS RIGHT_PARENTHESIS     { printf("utilisation de la méthode size  \n"); }
| NAME POINT PRINT LEFT_PARENTHESIS RIGHT_PARENTHESIS     { printf("utilisation de la méthode size  \n"); }
| NAME POINT FILL LEFT_PARENTHESIS nbrOrName RIGHT_PARENTHESIS { printf("fill(value) called \n"); }
| NAME POINT RANDOMIZE LEFT_PARENTHESIS nbrOrName COMMA nbrOrName RIGHT_PARENTHESIS { printf("randomize(min,max) called \n"); }
| NAME POINT MAX LEFT_PARENTHESIS RIGHT_PARENTHESIS           { printf("MAX() called \n"); }
| NAME POINT MAX LEFT_PARENTHESIS nbrOrName RIGHT_PARENTHESIS { printf("MAX(attr) called \n"); }
| NAME POINT MIN LEFT_PARENTHESIS RIGHT_PARENTHESIS           { printf("MIN() called \n"); }
| NAME POINT MIN LEFT_PARENTHESIS nbrOrName RIGHT_PARENTHESIS { printf("MIN(attr) called \n"); }
| NAME POINT SORT LEFT_PARENTHESIS RIGHT_PARENTHESIS            { printf("SORT() called \n"); }
| NAME POINT SORT LEFT_PARENTHESIS nbrOrName RIGHT_PARENTHESIS  { printf("SORT(attr) called \n"); }
| NAME POINT SUM LEFT_PARENTHESIS RIGHT_PARENTHESIS           { printf("SUM() called \n"); }
| NAME POINT SUM LEFT_PARENTHESIS nbrOrName RIGHT_PARENTHESIS { printf("SUM(attr) called \n"); }
| NAME POINT COUNT LEFT_PARENTHESIS nbrOrName RIGHT_PARENTHESIS             { printf("COUNT(val) called \n"); }
| NAME POINT COUNT LEFT_PARENTHESIS NAME COMMA nbrOrName RIGHT_PARENTHESIS  { printf("COUNT(attr,val) called \n"); }
| NAME POINT REMOVE LEFT_PARENTHESIS nbrOrName RIGHT_PARENTHESIS  { printf("remove(val) called \n"); }
| NAME POINT RANGE LEFT_PARENTHESIS RIGHT_PARENTHESIS             { printf("range() called \n"); }
| NAME POINT FIND LEFT_PARENTHESIS nbrOrName RIGHT_PARENTHESIS            { printf("find(val) called \n"); }
| NAME POINT FIND LEFT_PARENTHESIS NAME COMMA nbrOrName RIGHT_PARENTHESIS { printf("find(attr,val) called \n"); }
| NAME POINT PUT_FIRST LEFT_PARENTHESIS nbrOrName RIGHT_PARENTHESIS { printf("PUT_FIRST(elem) called \n"); }
| NAME POINT PUT_LAST LEFT_PARENTHESIS nbrOrName RIGHT_PARENTHESIS  { printf("PUT_Last(elem) called \n"); }
| NAME POINT REMOVE_LAST LEFT_PARENTHESIS RIGHT_PARENTHESIS   { printf("remove_Last() called \n"); }
| NAME POINT REMOVE_FIRST LEFT_PARENTHESIS RIGHT_PARENTHESIS  { printf("remove_Last() called \n"); }
| NAME POINT AVERAGE LEFT_PARENTHESIS RIGHT_PARENTHESIS           { printf("average() called \n"); }
| NAME POINT AVERAGE LEFT_PARENTHESIS nbrOrName RIGHT_PARENTHESIS { printf("average(attr) called \n"); }
| NAME POINT STORE LEFT_PARENTHESIS NAME RIGHT_PARENTHESIS    { printf("STORE(val) called \n"); }
| NAME POINT RESTORE LEFT_PARENTHESIS NAME RIGHT_PARENTHESIS  { printf("RESTORE(val) called \n"); }
| NAME POINT FIRST LEFT_PARENTHESIS RIGHT_PARENTHESIS   { printf("first() called \n"); }
| NAME POINT LAST LEFT_PARENTHESIS RIGHT_PARENTHESIS  { printf("last() called \n"); }
| NAME POINT REMOVE_AT LEFT_PARENTHESIS NUM_INTEGER RIGHT_PARENTHESIS               { printf("REMOVE_AT(pos) called \n"); }
| NAME POINT PUT_AT LEFT_PARENTHESIS NUM_INTEGER COMMA nbrOrName RIGHT_PARENTHESIS  { printf("put_at(pos, val) called \n"); }
| NAME POINT INSERT LEFT_PARENTHESIS RIGHT_PARENTHESIS                              { printf("insert() called \n"); }
| NAME POINT INSERT LEFT_PARENTHESIS nbrOrName COMMA nbrOrName RIGHT_PARENTHESIS    { printf("insert(key,val called \n"); }
| NAME POINT EXIST LEFT_PARENTHESIS nbrOrName RIGHT_PARENTHESIS                     { printf("insert() called \n"); }
;


%%

void yyerror(const std::string& mess){
    std::cerr << "Error found at line " << yylineno << " :  "<< mess << std::endl;
    existing_parsing_error= true;
}

// int
// yylex (void)
// {
//   int c;

//   /* Skip white space.  */
//   while ((c = getchar ()) == ' ' || c == '\t')
//     ++yylloc.last_column;

//   /* Step.  */
//   yylloc.first_line = yylloc.last_line;
//   yylloc.first_column = yylloc.last_column;

//   /* Process numbers.  */
//   if (isdigit (c))
//     {
//       yylval = c - '0';
//       ++yylloc.last_column;
//       while (isdigit (c = getchar ()))
//         {
//           ++yylloc.last_column;
//           yylval = yylval * 10 + c - '0';
//         }
//       ungetc (c, stdin);
//       return NUM;
//     }

//   /* Return end-of-input.  */
//   if (c == EOF)
//     return 0;

//   /* Return a single char, and update location.  */
//   if (c == '\n')
//     {
//       ++yylloc.last_line;
//       yylloc.last_column = 0;
//     }
//   else
//     ++yylloc.last_column;
//   return c;
// }


// void yyerror(const char *s, ...){
//   va_list ap;
//   va_start(ap, s);

//   if(yylloc.first_line)
//     fprintf(stderr, "%s:%d.%d-%d.%d: error: ", /*yylloc.filename,*/ yylloc.first_line, 
//      yylloc.first_column, yylloc.last_line, yylloc.last_column);
//   vfprintf(stderr, s, ap);
//   fprintf(stderr, "\n");
// }

void yyprint(const std::string& mess){
    std::cout << "[l" << yylineno << "] "<<mess  << std::endl;
}
